//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime ReservationStartDate { get; set; }
        public System.DateTime ReservationEndDate { get; set; }
        public int RoomId { get; set; }
        public byte NumberOfGuests { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual UserFamilyMember UserFamilyMember { get; set; }
    }
}
