//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFamilyMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserFamilyMember()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int UserFamilyMemberId { get; set; }
        public string MemberName { get; set; }
        public string UserId { get; set; }
        public string Photo { get; set; }
        public string SpecialNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
